### ISSUE TITLE
<Chunk src="..." /> for code-first images

### ISSUE THREAD

**Issue by ericclemmons** [Editmode-app/editmode-react#8]
@thomascullen is looking for a code-first way of handling images with chunks.

Typical React image resources are used like:

```js
import illustration from "./illustration.png";

return <img src={illustration} width={250} alt="" />
```

`<Chunk width={250} alt="" identifier="cnk_a2ab788a357bf06f140d" />` isn't that helpful, because it requires creating an image chunk first.

A better workflow is to find/replace `<img ` with `<Chunk ` and let the chunk get created once it's edited for the first time.

**Comment by ericclemmons** [comment]
@tonyennis145 I've found that the following _can_ work pretty easily:

```jsx
<Chunk src={illustration} width={250} alt="" />
```

The problem is, when clicked, there isn't a chunk to edit (yet):

> https://editmode.com/chunks/undefined/edit?iframe=true&...

What I'd like to do is instead frame the "New Chunk" experience, but with `type` and `content_key` already defined:

> https://editmode.com/projects/${projectId}/chunks/new?type=image&content_key=...

This way we only create the chunk if it's being customized.

**Comment by tonyennis145** [comment]
@ericclemmons got it. So we need to 

- Allow iframe embedding for chunks#new
- Pre-populate type & content_key from url parameters for chunks#new

Will get it on the backlog today :D

**Comment by ericclemmons** [comment]
@tonyennis145 @puuripurii @thomascullen See #11 for usage.  tldr; Replace `img` with `Chunk` and you should be good to go!  Clicking an editable image will show a "New Chunk" side-panel that uses the (default or explicitly defined) `contentKey`. Once saved, chunks load like usual!
